spreadsheet_url = "https://docs.google.com/spreadsheets/d/1d-K6dynZNd6NiwBxUXnqaeGzq5uvG3tXDnF6uQzpYRw/edit?gid=0#gid=0"

[gcp_service_account]
type = "service_account"
project_id = "diwali-orders-app"
private_key_id = "8af870413b5cd185464a0dd5aeb9d7585af19022"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCvy34SZCnO1n5c
S4O8LUgRAcFQwXF4lObHPBpn4jVIKviHQp0JpGKgiUJ3pkiFCsHSRfoOzwTvuVla
67yQUYrlMIvxNoUKBjmI+wBwuGCmI6eqaYcYZ/RUYsYlUOYbdbrVs2s/6jvTc1IX
r6DjvvHaG4/BwtjtMYC00YMRgtkDqdN8WJlU3CvTH9M+IBYMkW9EbZgBUeIw2GVy
frH9I/KADo4BkK+YnUITuGxoqYJ5SVjDAsJbzHpGszcT+f4DG4uvK0oHBCZ6Mp7B
f3XfqXOX9vr6Ks+l73In7rKW0MUIlmp8Nod3IBQWk6s3X4PbHqZNViU9mxLYxTUr
/s7IJCyxAgMBAAECggEAElF6+gViNmWTPgCX8ftJdc04JNc9gN5KRINSsJXJrdMd
efHC7arppJcc/B0RlDx8WTIVxiaEGgtXQHJNYEABAFQsVvayiwp+QxP9tiE+X/2Z
5nfv3gcSFpuC0IdjLQQZ85QKRlsdABIVoTZ5xlWiu9KwqpUIWAIXKnBlDyVyge8r
ZLIzVeSULgtNk8mVSzMTiD3HKn1nXQfxwS9DuEJG0leVI4vUZdrhulLOlZCobK7E
KIs9zxTpoLQl6fPJeiXeo7PmMX8fgMRqm5VAqN+kmPdxHQpy9rOe9dJ7L8K4ou8N
d5/U/gBt5CP+pDekHRGdhc1lY/sFVVplG1nOCJ3KqQKBgQDnJWIOC0tVYs0+6vis
ZWGFHunTWR3V2cCfC6BkaE2RwgHlfOhYBWmTnfug2Vfw01zANgXkkE97prC/bsjT
SfsdPx6LDjMWLnSJ5k9EElu5G0rEl0EbL4aKlz7BOR8DmQpPAtxZ4tQwI3hHVBCF
wtw1nxLgvYRapbjufg9gsr+4yQKBgQDCsn4BS8pBP0upy+fwuZ8QE152lgd0Qonq
VlE+s/vw6ATonYMnI+TbuzGoePtNs1GHkmAhqCFT3W9bRz5Mlwdx+22Gpc9HQ7pk
y9LzqwUvDUaA/pnzxYbMdIhM77stjhd5+b3eeGLRQ8JAMpAsgl2pSwjLo51+wsDW
BMMS4cGwqQKBgGrmAgwmswdhMzTG7IymMkyjeFYzH7Y4B3pGoT3ucvlW9ROSCc4z
aplHdgj0m1QYHAwUr/L9vpScCZ/u91eoHkdvWovK3FuEzoa8Caqcpujbs19p6EVP
XHSZ7/7ikPJUA814sDmtyp4cuVKbkSybasYttEhVvXFCtV0u1aPN5xbpAoGAVBFS
Syj4mhfEifqbmdvsjLpwTXAWo+KfPmorBpIctTbZ978bhGkBRsebd41VpYVKLOnN
THsWeOniTV2Dzvpfop3X+w3ZZIIgF6nS2pf70wc+bDCDNTkTLXEb8WyKO+9gv7BQ
haEhug4x8BplGnLoElNt5tAtDzD0pvTDboHAapECgYBWFO1FBJpYAzHwIQnX0k1Z
GxdnRGvra9QfaJgab5XLShvSkuNq24xDIXyvAlJZUi/0oD3tLt6ubUzf4zNW/NNk
NPjGAR31yKoeZ8Q+LeG60lVXTZsB7vFUXrafuorrKwD03D6gCdxt0osAURS4j3QC
881cQszwHz7pT6FcBNDiow==
-----END PRIVATE KEY-----
"""
client_email = "diwali-orders-service@diwali-orders-app.iam.gserviceaccount.com"
client_id = "116573320525446575056"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/diwali-orders-service%40diwali-orders-app.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
